# Generated by Django 5.0.6 on 2024-06-20 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemaddon',
            name='add_on',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='orderitemaddon',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='orderitemvariant',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='orderitemvariant',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='is_completed',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='myapp.OrderItem', to='myapp.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='AddOn',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='OrderItemAddOn',
        ),
        migrations.DeleteModel(
            name='OrderItemVariant',
        ),
        migrations.DeleteModel(
            name='VariantCategory',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
